### ISSUE TITLE
make errors about undefined taxa names visible outside makecldf

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/phlorest#13]
It would be useful if these errors could be caught outside of the makecldf process (e.g. by the check command). Wasn't sure the best way to do this though

https://github.com/phlorest/phlorest/blob/1f86ee228be461bd0b7bb5d4b38f3d0612e6b06c/src/phlorest/nexuslib.py#L43-L52

**Comment by xrotwang** [comment]
You mean to check the raw data **before** running (a possibly time-consuming) `makecldf`? That would be somewhat difficult, because right now, this checking is done on a tree that already comes out of quite a bit of pre-processing in `makecldf` (sampling, rescaling, etc.). So to make this independent of `makecldf` would require either duplicating some of the code or running such checks on **all** raw trees in `raw/` - detecting which is already a task of `makecldf` (which might eat up any speed ups by not running the full `makecldf`).

**Comment by xrotwang** [comment]
One could provide some code in `phlorest` to make this easy to integrate in `test.py`. I.e. run these checks on the CLDF output of `makecldf`. I think this would be useful because right now, none of these errors/warnings will result in an invalid CLDF dataset, but still potentially interfere with re-usability of the phylogeny.

**Comment by SimonGreenhill** [comment]
yeah, part of my "not knowing the best way to do this" was that I didn't think iterating over the trees twice was a good idea.

One way we could do it is to list these errors in the README.md or as a json file which a command like test/check could interrogate?

**Comment by SimonGreenhill** [comment]
closing this as wontfix (too complicated for little payoff)
